sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  global:
    - SUITE="tests/functional"
  matrix:
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.7
    - python: 2.6
      env: DJANGO=1.8
    - python: 2.6
      env: DJANGO=1.9
    - python: 2.6
      env: DJANGO=1.10

    - python: 3.3
      env: DJANGO=1.4
    - python: 3.3
      env: DJANGO=1.9
    - python: 3.3
      env: DJANGO=1.10

    - python: 3.4
      env: DJANGO=1.4

  include:
    - python: 2.7
      env: DJANGO=1.8 SUITE="tests/integration"

cache:
  directories:
    - $HOME/.cache/pip
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install django~=$DJANGO.0
  - pip install 'requests>=1.0' 'python-dateutil>=2.1' 'six>=1.2.0'
  - python setup.py install
script: py.test $SUITE
notifications:
  email:
    recipients:
      - ak@uploadcare.com
      - dm@uploadcare.com
      - vs@uploadcare.com
    on_success: change
    on_failure: change
