sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - DJANGO=1.4.20
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.8
  - DJANGO=1.8.2
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.7.8
    - python: 2.6
      env: DJANGO=1.8.2
    - python: 3.2
      env: DJANGO=1.4.20
    - python: 3.3
      env: DJANGO=1.4.20
    - python: 3.4
      env: DJANGO=1.4.20
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install django==$DJANGO
  - pip install 'requests>=1.0' 'python-dateutil>=2.1' 'six>=1.2.0'
  - python setup.py install
script: py.test tests
notifications:
  email:
    recipients:
      - ak@uploadcare.com
      - dm@uploadcare.com
    on_success: change
    on_failure: change
